#!/bin/bash
# ================================================================
# sync.sh — Skill Reference Synchronizer
# ================================================================
# Parses all skills/*/skill.md metadata and auto-generates
# the Skill References section in agent.md.
#
# Idempotent: safe to re-run after adding new skills.
# Uses sentinel comments to locate the replacement zone.
#
# Usage: bash scripts/sync.sh
# ================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AGENT_FILE="$REPO_ROOT/docs/agent-context/SKILL_REGISTRY.md"
SKILLS_DIR="$REPO_ROOT/skills"

echo "🔄 Syncing Skill References..."
echo "   Agent: $AGENT_FILE"
echo "   Skills: $SKILLS_DIR"
echo ""

# Verify files exist
if [ ! -f "$AGENT_FILE" ]; then
    echo "❌ Error: SKILL_REGISTRY.md not found at $AGENT_FILE"
    exit 1
fi

if [ ! -d "$SKILLS_DIR" ]; then
    echo "❌ Error: skills/ directory not found at $SKILLS_DIR"
    exit 1
fi

# Build the new Skill References table
TABLE_HEADER="| Skill | Path | Trigger | Scope |"
TABLE_SEPARATOR="|-------|------|---------|-------|"
TABLE_ROWS=""

for skill_dir in "$SKILLS_DIR"/*/; do
    skill_file="${skill_dir}skill.md"

    if [ ! -f "$skill_file" ]; then
        echo "   ⚠️  Skipping $skill_dir (no skill.md)"
        continue
    fi

    # Parse YAML frontmatter (only between first --- and second ---)
    name=$(awk '/^---$/{n++; next} n==1 && /^name:/{sub(/^name: *"?/, ""); sub(/"? *$/, ""); print; exit}' "$skill_file")
    trigger=$(awk '/^---$/{n++; next} n==1 && /^trigger:/{sub(/^trigger: *"?/, ""); sub(/"? *$/, ""); print; exit}' "$skill_file")
    scope=$(awk '/^---$/{n++; next} n==1 && /^scope:/{sub(/^scope: *"?/, ""); sub(/"? *$/, ""); print; exit}' "$skill_file")

    # Get relative path from repo root
    rel_path="${skill_file#$REPO_ROOT/}"

    if [ -n "$name" ]; then
        TABLE_ROWS="${TABLE_ROWS}| \`${name}\` | \`${rel_path}\` | ${trigger} | \`${scope}\` |\n"
        echo "   ✅ ${name} → ${rel_path}"
    else
        echo "   ⚠️  ${skill_dir} has no 'name' in metadata"
    fi
done

# Generate the replacement block
REPLACEMENT=$(printf "%s\n%s\n%b" "$TABLE_HEADER" "$TABLE_SEPARATOR" "$TABLE_ROWS")

# Replace content between sentinel comments in agent.md
BEGIN_SENTINEL="<!-- BEGIN SKILL REFERENCES (auto-generated by scripts/sync.sh) -->"
END_SENTINEL="<!-- END SKILL REFERENCES -->"

if ! grep -q "$BEGIN_SENTINEL" "$AGENT_FILE"; then
    echo ""
    echo "❌ Error: Sentinel comment not found in SKILL_REGISTRY.md"
    echo "   Expected: $BEGIN_SENTINEL"
    echo "   Add this comment to SKILL_REGISTRY.md to enable auto-sync."
    exit 1
fi

# Use awk to replace the block between sentinels
awk -v begin="$BEGIN_SENTINEL" -v end="$END_SENTINEL" -v replacement="$REPLACEMENT" '
    $0 == begin { print; print ""; print replacement; skip=1; next }
    $0 == end { skip=0; print ""; print; next }
    !skip { print }
' "$AGENT_FILE" > "${AGENT_FILE}.tmp"

mv "${AGENT_FILE}.tmp" "$AGENT_FILE"

echo ""
echo "🎉 Skill References synced in agent.md ($(echo -e "$TABLE_ROWS" | grep -c '|') skills)"
